- hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact: join_command={{ join_command_raw.stdout }}


- hosts: workers
  become: yes
  tasks:

    - name: join cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'] }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: master
  become: yes
  tasks: 
    - name: Verificando o cluster
      shell: kubectl get nodes
      register: nodeup

    - debug:
        var: nodeup